name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#    - name: Docker meta
#      id: meta
#      uses: docker/metadata-action@v4
#      with:
#        images: delik8shub/streampark
#        tags: |
#          type=raw,value=latest,enable={{is_default_branch}}
#          type=ref,event=tag
#          type=ref,event=branch

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/rddns:latest

